baseURL = "https://g-pacheco.github.io/"
languageCode = "en-us"
title = "George Pacheco:~#"
theme = "archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 3 # articles per page

[params]
	mode = "dark" # color-mode → light, dark or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.


# Social Tags

[[params.social]]
name = "Work"
icon = "map-pin"
url = "https://www.google.com/maps/place/DTU+Aqua/@56.1536297,9.5608707,17z/data=!4m5!3m4!1s0x464b8b0595bfcff5:0xb5912d83dbe1f13b!8m2!3d56.1541738!4d9.561381"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:ganpa@aqua.dtu.dk"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/pacheco-george"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/george-pacheco-2281b1106/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/menino.pacheco/"

# Main menu Items

[[menu.main]]
name = "Bio/"
url = "/Bio"
weight = 1

[[menu.main]]
name = "Projects/"
url = "/Projects"
weight = 2

[[menu.main]]
name = "Publications/"
url = "/Publications"
weight = 3