baseURL = "https://g-pacheco.github.io/"
googleAnalytics = "G-6HEVWZ2M09"
languageCode = "en-us"
title = "George Pacheco:~"
theme = "archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 3 # articles per page

[params]
	mode = "dark" # color-mode → light, dark or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.

# Social Tags

[[params.firsticon]]
name = "Working Place"
prefix = "fa"
icon = "compass"
type = "far"
url = "https://www.google.com/maps/place/DTU+Aqua/@56.1536297,9.5608707,17z/data=!4m5!3m4!1s0x464b8b0595bfcff5:0xb5912d83dbe1f13b!8m2!3d56.1541738!4d9.561381"

[[params.icons]]
name = "Email"
prefix = "fa"
icon = "envelope"
type = "far"
url = "mailto:ganpa@aqua.dtu.dk"

[[params.icons]]
name = "LinkedIn"
prefix = "fa"
icon = "linkedin-in"
type = "fab"
url = "https://www.linkedin.com/in/george-pacheco-2281b1106/"

[[params.icons]]
name = "ORCID"
prefix = "ai"
icon = "orcid-square"
type = "ai"
url = "https://orcid.org/0000-0002-9367-6813"

[[params.icons]]
name = "Google Scholar"
prefix = "ai"
icon = "google-scholar-square"
type = "ai"
url = "https://scholar.google.dk/citations?user=FSCWyqAAAAAJ&hl=en"

[[params.icons]]
name = "GitHub"
prefix = "fa"
icon = "github"
type = "fa"
url = "https://github.com/g-pacheco"

[[params.lasticon]]
name = "Instagram"
prefix = "fa"
icon = "instagram"
type = "fa"
url = "https://www.instagram.com/menino.pacheco/"


# Main menu Items

[[menu.main]]
name = "News/"
url = "/News"
weight = 1

[[menu.main]]
name = "CV/"
url = "/CV"
weight = 2

[[menu.main]]
name = "Publications/"
url = "/Publications"
weight = 4

[[menu.main]]
name = "myReads/"
url = "/myReads"
weight = 5