baseURL = "https://g-pacheco.github.io/"
googleAnalytics = "G-6HEVWZ2M09"
languageCode = "en-us"
title = "George Pacheco:~"
theme = "archie"
description = "Personal webpage of evolutionary biologist George Pacheco, PhD."

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 3 # articles per page
enableEmoji = true

[params]
	favicon = "https://img.icons8.com/fluency/96/000000/octopus.png"

[params.site]
	mode = "light" # color-mode → light, dark or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	typeformid = "u6nTL7" # Required
	typeformuser = "myuser" # Optional
	typeformwidth = "100%" # Optional
	typeformheight = "800px" # Optional
	
# Social Tags

[[params.firsticon]]
name = "Working Place"
prefix = "fa"
icon = "compass"
type = "far"
url = "https://www.google.com/maps/place/Kristine+Bonnevies+hus/@59.9380751,10.7224508,17z/data=!4m13!1m7!3m6!1s0x46416de767a63a63:0x4df685f0b22d4fcb!2sBlindernveien+31,+0371+Oslo!3b1!8m2!3d59.9380724!4d10.7246395!3m4!1s0x46416de751f5a9b5:0xd2a3806479c4436c!8m2!3d59.9383743!4d10.7219023"

[[params.icons]]
name = "Email"
prefix = "fa"
icon = "envelope"
type = "far"
url = "mailto:george.pacheco@ibv.uio.no"

[[params.icons]]
name = "ORCID"
prefix = "ai"
icon = "orcid"
type = "ai"
url = "https://orcid.org/0000-0002-9367-6813"

[[params.icons]]
name = "Google Scholar"
prefix = "ai"
icon = "google-scholar"
type = "ai"
url = "https://scholar.google.dk/citations?user=FSCWyqAAAAAJ&hl=en"

[[params.icons]]
name = "Lattes"
prefix = "ai"
icon = "lattes"
type = "ai"
url = "http://lattes.cnpq.br/8779597063731617"

[[params.icons]]
name = "GitHub"
prefix = "fa"
icon = "github"
type = "fa"
url = "https://github.com/g-pacheco"

[[params.icons]]
name = "bluesky"
prefix = "fa"
icon = "bluesky"
type = "fab"
url = "https://bsky.app/profile/pachecoevolbio.bsky.social"

[[params.icons]]
name = "Goodreads"
prefix = "fa"
icon = "goodreads-g"
type = "fab"
url = "https://www.goodreads.com/user/show/91609313-george-pacheco"

[[params.lasticon]]
name = "Instagram"
prefix = "fa"
icon = "instagram"
type = "fa"
url = "https://www.instagram.com/menino.pacheco/"

#[[params.lasticon]]
#ame = "YouTube"
#prefix = "fa"
#icon = "youtube"
#type = "fa"
#url = "https://www.youtube.com/channel/UCcjP3uH7VFk4n_lIc4bgxbQ"

# Main menu Items

[[menu.main]]
name = "News/"
url = "/News"
weight = 1

[[menu.main]]
name = "CV/"
url = "/CV"
weight = 2

[[menu.main]]
name = "Research/"
url = "/Research"
weight = 3

[[menu.main]]
name = "Publications/"
url = "/Publications"
weight = 4

[[menu.main]]
name = "Reads/"
url = "/Reads"
weight = 5

[[menu.main]]
name = "Gallery/"
url = "/Gallery"
weight = 6

[[menu.main]]
name = "Contact/"
url = "/Contact"
weight = 7